### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by parasiteoflife** [LordRusk/goscrape#1]
Hey, can you make a Windows build? I want to try your software.
Thanks.

**Comment by LordRusk** [comment]
i believe `go get` works on windows if you have go installed, and I wont be able to compile anything until sunday night this week due to family stuff, but i'll be sure to as soon as I can!

**Comment by LordRusk** [comment]
@parasiteoflife Windows builds included in [v1.3.1](https://github.com/LordRusk/goscrape/releases/tag/v1.3.1)

**Comment by parasiteoflife** [comment]
Thank you!
